-- phpMyAdmin SQL Dump
-- version 4.1.2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jul 09, 2015 at 06:40 PM
-- Server version: 5.6.13
-- PHP Version: 5.6.9

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `polling`
--

-- --------------------------------------------------------

--
-- Table structure for table `candidate`
--

CREATE TABLE IF NOT EXISTS `candidate` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `poll_id` int(3) NOT NULL,
  `name` varchar(255) NOT NULL,
  `name_np` varchar(255) CHARACTER SET utf32 COLLATE utf32_bin NOT NULL,
  `organization` varchar(255) NOT NULL,
  `organization_np` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `detail` text NOT NULL,
  `detail_np` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `photo` varchar(255) NOT NULL,
  `votes` int(6) NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `active` int(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=49 ;

--
-- Dumping data for table `candidate`
--

INSERT INTO `candidate` (`id`, `poll_id`, `name`, `name_np`, `organization`, `organization_np`, `detail`, `detail_np`, `photo`, `votes`, `timestamp`, `active`) VALUES
(1, 1, 'Yuvaraj Bhandari', 'युवराज भण्डारी', 'Resunga Chetana Krishi Samuha', 'रेसुङ्गा चेतना कृषि समूह', 'Although started as a vegetable farm, Mr. Yuvaraj Bhandari’s business has already expanded to include fish farm, poultry farm, and a goat farm in just two years. While many businesses only want to earn big profits, Mr. Bhandari in the next three years wants to strengthen and systematize his business to provide opportunities for students, researchers do they can visit his farm for educational purposes.', 'युवराज भण्डारी रेसुङ्गा नगरपालिकामा संयुक्त रुपमा कृषि फार्म संचालन गर्नुहुन्छ । उहाँको फार्ममा माछा, कुखुरा र बाख्रापालनका साथै तरकारी खेती गरिरहनु भएको छ । फर्मलाई थप व्यवस्थित बनाइ, उत्पादन वृद्धि गरी युवाविद्यार्थीको लागि अध्ययन केन्द्र बनाउने सोँच उहाँहरुको रहेको छ । साथै फर्ममा आन्तरिक तथा बाह्य पर्यटक भित्राउने योजना उहाँहरुको रहेको छ ।', 'img/profiles/yuvraj.jpg', 0, '2015-07-09 12:51:38', 1),
(4, 1, 'Tulsa Pandey', 'तुलसा पाण्डे', 'Krishi Utpadan', 'कृषि उत्पादन', 'Litchi, lemon, orange, banana are among the few things that Ms. Tulsa Pandey produces in her fruit orchard. What differentiates her orchard from others  is that she produces everything in a very systematic and scientific way. With this system, she hopes to increase her business from 71 plants to 500 plants in the next 3 years and also produce non seasonal vegetables.', 'तुलसा पाण्डे अश्लेवा गाविसमा बसी तरकारी तथा फलफूल उत्पादन गर्नुहुन्छ । उहाँले वेमौसमी तरकारीका साथै लिची, सुन्तला, कागती, केरा उत्पादन गर्नुहुन्छ । उहाँले आफ्नो व्यवसायलाई नमूना बनाउने सोँच लिनु भएको छ । आगामी दिनमा व्यवसायलाई थप विस्तार गर्ने योजना उहाँले बनाउनु भएको छ ।', 'img/profiles/tulsa-pandey.jpg', 0, '2015-07-09 12:51:50', 1),
(5, 1, 'Yuvaraj Gyawali', 'युवराज ज्ञवाली', 'Gyawali Litchi Utpadan', 'ज्ञवाली लिची उत्पादन', 'A successful entrepreneur, Mr. Yuvaraj Gyawali has not only captured the market for litchi plants, but also successfully proliferated his business such that there are litchi plants in every free space in the farms of his village. In the next three years, he plans to expand his market outreach by building another greenhouse and producing at least 5000 litchi plants annually.', 'युवराज ज्ञवाली रुरु गाविसमा बसी लिची उत्पादन गर्नुहुन्छ । उहाँ आफूमात्र होइन सिंगो गाउँ नै लिची उत्पादनमा लगाउन सहयोग गर्नु भएको छ । आगामी दिनमा ग्रिनहाउन बनाइ ठूलो मात्रामा लिचीको विरुवा उत्पादन गर्ने र आ1फ्नो बाँकी जमिनमा पनि लिची विरुवा थप गर्ने योजना बनाउनु भएको छ ।', 'img/profiles/yuvaraj-g.jpg', 0, '2015-07-09 12:52:11', 1),
(7, 1, 'Tika Ram Kafle', 'टिकाराम काफ्ले', 'Mountain Organic Krishi Farm', 'माउण्टेन अर्गानिक कृषि फार्म', 'Mr. Tika Ram Kafle’s objective of his agro-business is not just to earn a living, but also to establish himself as a successful farmer and spread a positive message about agriculture in his village. He currently grows vegetables, coffee, sugarcane, and sells milk from the cows. In the next three years, he envisions bolstering his business by selling sugarcane juice and buying five more cows to increase milk production.', 'टिकाराम काफ्ले हर्दिनेटामा बसी अर्गानिक कृषि फार्म संचालन गर्नुहुन्छ । उहाँले तरकारी, कफी, खुदो, गुँड र दूध उत्पादन गरिरहनु भएको छ । उहाँले आफ्नो फर्मलाई नमूना बनाइ अरुलाई उत्प्रेरणा पैदा गर्न चाहनुहुन्छ । आगामी दिनमा व्यवसायलाई विस्तार गरी उत्पादनलाई वृद्धि गर्ने योजना बनाउनु भएको छ ।', 'img/profiles/tika_ram_kafle.jpg', 0, '2015-07-06 19:57:39', 1),
(8, 1, 'Tek Bahadur Rajali', 'टेकबहादुर रजाली', 'Byawasaik Tarkari Kheti', 'व्यवसायिक तरकारी खेती', 'Recognized by the District Agriculture Development Office and the Village Development Committee for running a successful business, Mr. Tek Bahadur Rajali already has seventeen years of experience in growing vegetables, producing fish and honey. With this extensive experience and a strong vision for the future, he plans to grow his honey farm from 10 hives to 50 hives, build one more fish pond and expand his vegetable farm to 6-7 ropanis in the next three years.', 'टेकबहादुर रजाली, बलिथुम गाविसमा बसी तरकारी खेती, मौरीपालन र माछापालन गर्नुहुन्छ । उहाँले १७ वर्षदेखि यो व्यवसाय गरिरहनु भएको छ । आफ्नो व्यवसायलाई थप विस्तार गर्ने योजना बनाउनु भएको छ । मेहनत गरे कृषि व्यवसायमा राम्रो संभावना छ भन्ने विश्वास उहाँको रहेको छ । कृषिको व्यवसायीकरणबाट नेपालको आर्थिक विकास गर्न सकिने मान्यता उहाँको छ । ', 'img/profiles/tek_bahadur_rijal.jpg', 0, '2015-07-06 19:59:28', 1),
(9, 1, 'Tanka Prasad Shrestha', 'टंकप्रसाद श्रेष्ठ', 'Bhimsen Gai Farm', 'भीमसेन गाइ फार्म', 'What distinguishes Mr. Tanka Prasad Shrestha’s milk production and farming business is his determination, drive, and hard work to provide the best service to his customers and to learn continuously. In the next three years, he plans to his expand market outreach by investing in physical facilities, newer technologies, and exploring possible financial sources in order to increase both the quantity and quality of his production.', 'टंकप्रसाद श्रेष्ठ बलेटक्सार गाविसमा बसी गाइपालन व्यवसाय गरिरहनु भएको छ । उपभोक्ताको मागबमोजिम गुणस्तरीय दूध बिक्री गरी आयआर्जन गर्न यो व्यवसाय गर्नु भएको छ । दूध उत्पादन व्यवसायमा राम्रो संभावना देख्ने उहाँले उपभोक्ताको माग, बजारको अवस्था हेरेर व्यवसायलाई विस्तार गर्ने योजना बनाउनु भएको छ । आगामी दिनमा व्यवसायमा थप लगानी र आधुनिक प्रविधि प्रयोग गरी दूधको उत्पादन र गुणस्तर दुवै बढाउने सोच उहाँमा रहेको छ ।', 'img/profiles/tanka_prasad_shrestha.jpg', 0, '2015-07-06 21:24:38', 1),
(10, 1, 'Surya Bahadur Kunwar Magar', 'सूर्यबहादुर कुँवर मगर', 'Mauri Palan', 'मगर मौरी पालन', 'For Mr. Surya Bahadur Kunwar who enjoys working hard, he’s found the perfect livelihood: working with the hardworking bees in his bee farming and selling honey. He uses modern hives, honey collector, gloves and bee veils to produce and supply organic honey both in and outside his district. Believing that the market for bee products has great potential, he plans to increase the number of beehives by 2.5 times to increase both honey production and sale of hives and expand market outreach in the coming three years.', 'सूर्यबहादुर कुँवर मगर बलिथुम गाविसको मौरी पालक कृषक हुनुहुन्छ । उहाँले आधुनिक तरिकाबाट मौरी पालन गरिरहनु भएको छ । उहाँले उत्पादन गरेको अर्गानिक मह गुल्मी र गुल्मीबाहिर विक्री  हुन्छ । आगामी दिनमा व्यवसाय विस्तार गर्ने योजना बनाउनु भएका उहाँले यस व्यवसायले रोजगारी बृद्धि गर्ने राम्रो संभावना देख्नु हुन्छ । ', 'img/profiles/surya_bahadur.jpg', 0, '2015-07-06 21:24:38', 1),
(11, 1, 'Shambhu Pandey', 'शम्भु पाण्डे', 'Shree Siddhababa Gaushala Krishi Udhyog', 'श्री सिद्धबाबा गौशाला कृषि उद्योग ', 'An avid work enthusiast, Mr. Shambhu Pandey runs a business that produces milk and milk products. In the next three years, he envisions strengthening his business by increasing the number of cows from 15 to 50, and increase the pasture land for better mobility and improved living conditions for the cows.', 'शम्भु पाण्डे गुल्मी जिल्लाको तम्घासमा गाइपालन व्यवसाय गरिरहनु भएको छ । गुणस्तरीय दूधको माग पूरा गरी आयआर्जन गर्न यो व्यवसाय सुरु भएको हो । उहाँले धेरै लगानी गरी व्यवस्थित गोठ निर्माण गरी गाइ पालन गर्नु भएको छ । आगामी दिनमा गाइ थपी दूध उत्पादन वृद्धि गर्ने र नमूना गाइ फार्म बनाउने लक्ष्य उहाँहरुको छ । ', 'img/profile/Shambhu_Pandey.jpg', 0, '2015-07-07 10:09:59', 1),
(12, 1, 'Seshnarayan Marasini', 'शेषनारायण मरासिनी', 'Bhutkuwa Bakhra Palan Farm', ' भटकुवा बाख्रापालन फार्म ', 'Mr. Seshnarayan Marasini’s objective is not just to run a business that produces fresh goat meat, but to establish a highly succesful one. He envisions inspiring other community members to take up animal husbandry to produce meat that will be enough for the whole nation, and even export the excess amount to other countries. In the coming years, he plans to expand the physical facilities and use modern equipment to increase supply in the ', 'शेषनारायण मरासिनी रुरु गाविसमा बसी व्यवसायिक बाख्रा फर्मको संचालन गर्नुहुन्छ । उहाँले नेपालमा उच्च माग रहेको मासुको आपूर्ति गरी आयआर्जन गर्न बाख्रा फर्म संचालन गर्नु भएको हो । उहाँले गुल्मी तथा जिल्लाबाहिर बाख्रा निर्यात गर्ने लक्ष्य राख्नु भएको छ । व्यवसायको विस्तार गरी थप रोजगारी सिर्जना गर्ने र सफल उद्यमी बन्ने योजना उहाँले बनाउनु भएको छ ।', 'img/profile/Seshnarayan_Marasini.jpg', 0, '2015-07-07 10:09:59', 1),
(13, 1, 'Rabilal Pant', 'रविलाल पन्त', 'Gaurav Dudh Dairy tatha Prashodhan Kendra', 'गौरव डेरी तथा प्रशोधन केन्द्र', 'Mr. Rabilal Panth envisions making his village free from alcoholism and gambling by expanding his dairy farm that produces items like milk, ghee, curd, kuwa and other dairy products. You may wonder how, but Mr. Panth knows that by establishing a milk processing plant in his village and employing youths not only can he channel their energy into production but also make his village dairy-sufficient.\r\n', 'रविलाल पन्त रुरु गाविसमा बसी दूग्ध व्यवसाय गर्नुुहुन्छ । उहाँले गाउँलाई रक्सी र जुवातासबाट मुक्त पार्न कृषिमा आधारित उद्यमशीलताको विकास हुनुपर्ने मान्यता राख्नुहुन्छ । गुणस्तरीय दूध र दूधजन्य परिकार उत्पादन गरी उपभोगमा वृद्धि गराइ व्यवसाय प्रवद्र्धन गर्ने योजना उहाँको रहेको छ । दूधको बढ्दो मागलाई पूरा गर्न आफ्नो व्यवसायमा दूध प्रशोधन मेशीन राख्ने र रोजगारीको सिर्जना गर्ने योजना उहाँको रहेको छ ।', 'img/profile/Rabilal_Pant.jpg', 0, '2015-07-07 10:09:59', 1),
(14, 1, 'Prem Narayan Parajuli', 'प्रेमनारायण पराजुली', 'Parajuli Krishi Tatha Nursery Farm', 'पराजुली कृषि तथा नर्सरी फार्म', 'For Prem Narayan Parajuli, producing and selling fresh vegetables and earning a living is not his only priority. As a successful entrepreneur, he knows the importance of good quality products; therefore in the coming three years, he wants to use organic manure, good quality seeds and modern equipment not only to grow fresh vegetables, but also to support other local farmers by supplying healthy and prolific vegetable saplings.\r\n', 'प्रेमनारायण पराजुली तुराङ्ग गाविसमा बसी ताजा तरकारी उत्पादन गर्ने उद्यमी हुनुहुन्छ । उहाँ आधुनिक प्रविधिको प्रयोग गरी अर्गानिक तरकारीको उत्पादन बढाउने योजनामा हुनुहुन्छ । अर्गानिक, स्वस्थकर तरकारीको माग पूरा गरी सफल उद्यमी भई गाउँका अरु युवाहरुलाई पनि यस पेशामा आकर्षिक गर्ने सोच उहाँमा रहेको छ । कृषिको व्यवसायीकरणले मात्र आर्थिक संमृद्धि गर्नुपर्छ भन्ने मान्यता उहाँले लिनु भएको छ ।', 'img/profile/Prem_Narayan_Parajuli.jpg', 0, '2015-07-07 10:14:17', 1),
(15, 1, ' Niroj Marasini', 'निरोज मरासिनी', 'Resunga Saune Bahudesya Krishi Farm', 'रेसुङ्गा बहुउद्देश्यीय कृषि फर्म', 'Resunga Bahudesya Krishi Farm  is unique-- established with collective investment from 26 investors, this business produces everything from fresh vegetables to milk, meat and fish. Along with this edge, Mr Niroj Marasini wants to work harder and smarter so that in the next three years they can cover the national market and expand their collective business to set an example for everyone in the nation.\r\n', 'निरोज मरासिनी संयुक्त रुपमा रेसुङ्गा नगरपालिका–३ मा संचालित कृषि फर्मको नेतृत्व गर्नुहुन्छ । ताजा तरकारी, दूध उत्पादन, बाख्रापालन र माछापालन गर्ने उहाँहरुको फर्ममा २६ जना युवा उद्यमीहरुको लगानी रहेको छ । आगामी दिनमा देशकै नमूना कृषि फार्मको बनाउने अठोट उहाँहरुको छ । नमूना कृषि फर्ममार्फत विदेश जाने युवाहरुलाई देशमै केही गर्न सकिन्छ भन्ने आत्मविश्वास जगाउन सकिने विश्वास उहाँहरुको छ ।  ', ' img/profile/Niroj_Marasini.jpg', 0, '2015-07-07 11:03:03', 1),
(16, 1, 'Narayan Pokharel', 'नारायण पोखरेल', 'Adarsha Falful Prashodhan kendra', 'आदर्श फलफूल प्रशोधन केन्द्र', 'Mr. Narayan Pokharel capitalized on his skills and established a business to process fruits and vegetables into juice, sauce, pickles, sweets etc. so that these perishable items could be used even during off seasons. In order to best utilize his high potential market, he plans to establish a modern processing plant, train more people in this business, and sell his processed products far and wide through an extensive distribution network.', 'नारायण पोखरेल नयाँगाउँ गाविसमा बसी फलफूलको जुस, जाम, मिठाइ तथा अचार उत्पादन गर्ने व्यवसायमा संलग्न हुनुहुन्छ । उहाँको आफ्नै सुन्तला बगैचा समेत रहेको छ । उहाँले उत्पादन गरेका जुस, जाम, तथा अचार स्थानीय बजारमा खपत हुने गरेको छ । आगामी दिनमा आधुनिक प्रशोधन गर्ने मेशीन प्रयोग गरी व्यवसाय विस्तार गर्ने योजना उहाँको रहेको छ । ', 'img/profile/Narayan_Pokharel.jpg', 0, '2015-07-07 10:37:10', 1),
(17, 1, 'Mr & Mrs. Aale Kumal', 'आले कुमाल', 'Sita Ceramic Udhyog', 'सीता सेरामिक्स उद्योग ', 'Kumal embarked on his business venture of producing ceramic utensils with a vision to preserve Nepal’s traditional heritage of ceramic craft. The use of modern machinery and technology has helped him manufacture in a more efficient way and he hopes to export his products in the coming days. Besides using locally available resources, his enterprise has been providing employment opportunities to many youths and thus, preventing them from migrating abroad.\r\n', 'आले कुमाल अमरपुर गाविसको बुल्ममा बसेर परम्परागत रुपमा उत्पादन गरिँदै आएको माटाका भाँडा उत्पादन गर्ने उद्योगी हुनुहुन्छ । उहाँले आफ्नो उद्योगमा आधुनिक प्रविधिको प्रयोग गरी समयसापेक्ष माटाका वस्तु निर्माण गर्ने उद्देश्यले यो उद्योग सुरुवात गर्नु भएको हो । स्थानीय स्रोतको प्रयोग गरी संचालन गरिने यस उद्योगका माध्यमबाट युवा रोजगारीको सिर्जना गरी विदेश पलायन रोक्ने लक्ष्य रहेको छ । ', 'img/profile/Aale_Kumal.jpg', 0, '2015-07-07 10:37:19', 1),
(18, 1, 'Moom Bahadur Bhalami', 'मुमबहादुर भलामी', 'Bhalami Vyawasaik Bangur Palan', 'भलामी व्यवसायिक वंगुर पालन', 'Mr. Moom Bahadur Bhalami’s resource optimization skills are impressive; he not only grows pigs for his meat business, but also uses pig’s droppings as manure for his vegetable farms. In three years, he plans to expand his business systematically by buying more land and building more cages to grow more pigs to increase meat production. He also plans to start fish farming and using the manure from pigs for extensive vegetable farming.', 'मुमबहादुर भलामी तम्घासमा बसी वंगुर पालनमा सक्रिय युवा व्यवसायी हुनुहुन्छ । उहाँले वंगुरमात्र साथै तरकारी उत्पादन गर्नुहुन्छ । उहाँले वंगुरको माग आपूर्ति गरी आयआर्जन वृद्धि गर्र्न यो व्यवसाय गर्नुभएको हो । आगामी दिनमा वंगुरको व्यवस्थित खोर निर्माण गर्ने, थप जग्गा भाडामा लिइ व्यवसाय विस्तार गर्ने योजना उहाँको रहेको छ । \r\n', 'img/profile/Moom_Bahadur_Bhalami.jpg', 0, '2015-07-07 10:37:29', 1),
(19, 1, 'Bamgha Dugdha Utpaadan Sahakari Sanstha', 'बम्घा दुध उत्पादन सहकारी संस्था ', 'Bamgha Dugdha Utpaadan Sahakari Sanstha', 'बम्घा दुध उत्पादन सहकारी संस्था ', 'The only cooperative running dairy production, Bamgha Dugdha Utpaadan Sahakari Sanstha uses modern tools and equipment to produce milk products. In addition to growing this cooperative, their aim is to modernize animal husbandry sector and to attract low income households towards the sector. To that end, within the next three years they plan to connect farmers engaged in animal husbandry with training programs for capacity building and using modern technology.', 'बम्घा गाविसमा संचालित बम्घा दुध उत्पादन सहकारी संस्थाले आधुनिक सीप र प्रविधि प्रयोग गरी दूध व्यवसाय गरिरहेको छ । यस सहकारीले निम्न आय भएका र परम्परागत पशुपालन गरिरहेका कृषकहरुलाई दूध उत्पादनमा लगाइ आयआर्जनका कार्यमा सहयोग पुराएको छ । आगामी तीन वर्षमा ग्रामीण कृषकलाई आधुनिक र व्यवसायिक दुध उत्पादनमा लगाइ दूध व्यवसायलाई विकास गर्ने लक्ष्य लिएको छ । यसका लागि कृषकलाई क्षमता विकास गरी  दूग्ध व्यवसाय प्रवद्र्धन गर्ने कार्य संचालन गरिरहेको छ ।\r\n', 'img/profile/Bamgha.jpg', 0, '2015-07-07 10:37:38', 1),
(20, 1, 'Madan Shrestha', 'मदन श्रेष्ठ', 'Heubesi Bahu Udeshya Krishi Samuha', 'हिउँवेशी बहुउद्देश्यीय कृषि समूह', 'A dynamic youth entrepreneur, Mr. Madan Shrestha runs his family business that sells fruits and vegetable saplings and produces vegetables both collectively and independently. Young he may be, but his dreams are big; in the next three years, he envisions doubling his farm production by expanding his farmland to two times the current area, cultivate newer varieties of fruits and herbs, and also venture into fish farming and animal husbandry.\r\n', 'मदन श्रेष्ठ बम्घा गाविसमा बसी तरकारी तथा फलफूल उत्पादन गर्ने युवा उद्यमी हुनुहुन्छ । उहाँले १८ वर्षको उमेरमै आफूलाई कृषि उद्यममा सक्रिय बनाउनु भएको छ । तरकारी र फलफूलको बढ्दो माग पूरा गरी आयआर्जन गर्न उहाँ व्यवसायिक कृषिमा लाग्नु भएको हो । आगामी दिनमा आफ्नो व्यवसायलाई समयसापेक्ष विकास गरी विस्तार गर्ने योजना उहाँको रहेको छ । \r\n', 'img/profile/Madan_Shrestha.jpg', 0, '2015-07-07 10:37:51', 1),
(21, 1, 'Shree Nawa Durga Krishi Sahakari Sanstha', 'श्री नवदुर्गा कृषि सहकारी संस्था ', 'Shree Nawa Durga Krishi Sahakari Sanstha', 'श्री नवदुर्गा कृषि सहकारी संस्था ', 'In order to support local farmers and make them self-reliant , Shree Nawa Durga Krishi Sahakari Sanstha provides low-interest loans to the farmers in their village. In the coming years, they plan to use the interest and investment profit to support more farmers and entrepreneurs in their village and beyond.', 'श्री नवदुर्गा कृषि सहकारी संस्था कृषकहरुलाई व्यवसायीकरण गर्न अगुवाइ गरिरहेको सहकारी हो । यसले गौडाकोट र विरबास गाविसमा काम गरिरहेको छ । यसले कृषकहरुलाई व्यवसायिक उत्पादनमा लगाउने र सहकारीले बजारीकरणमा सहयोग गर्ने गर्दछ । साथै कृषकहरुका लागि पूँजी, प्रविधि र सीप उपलब्ध गराउने कार्य समेत सहकारीले गरिरहेको छ । हाल दुई गाविसका कृषकहरुलाई यसले नेतृत्व दिइरहेको छ । यस सहकारीको अगुवाईमा दूध, फलफूल तरकारी, मासु उत्पादन भइरहेको छ  । ', 'img/profile/shree.jpg', 0, '2015-07-07 10:37:59', 1),
(22, 1, 'Krishna Prasad Bhandari', 'कृष्णप्रसाद भण्डारी', ' Namuna Bakhrapalan Farm', ' नमूना बाख्रा पालन फार्म ', 'After coming back from working abroad, Mr. Krishna Prasad established Namuna Bakhapalan Farm to make his village self-sufficient in meat production and to provide jobs to unemployed youths in his village.  In the coming three years, he plans to increase meat production by increasing the number of goats, expanding pasture land for grazing and using progressive technology in rearing the goats.', 'कृष्णप्रसाद भण्डारी लामोसमयको विदेश बसाइबाट फर्केर रुपाकोट गाविसमा व्यवसायिक बाख्रा फार्म संचालन गर्ने युवा व्यवसायी हुुनुहुन्छ । बढ्दो मासुको माग पूरा गर्न उहाँले यो फार्म संचालन गर्नु भएको हो । व्यवसायिक फार्मको विस्तार गर्ने र रोजगारीको सिर्जना गरी गर्ने लक्ष्य योजना उहाँले बनाउनु भएको छ । \r\n', 'img/profile/Krishna_Prasad_Bhandari.jpg', 0, '2015-07-07 10:38:09', 1),
(23, 1, 'Krishna Prasad Gyawali', 'कृष्णप्रसाद ज्ञवाली', 'Shree Krishna Ekikrit Falful Tatha Macha Palan', ' श्री कृष्ण एकीकृत फलफूल तथा माछापालन', 'Seeing the market flooded with fishes produced using chemicals, Mr. Krishna Prasad Gyawali’s started his fish farming business to produce organic and healthy fishes. Currently he has only two small ponds, but in the future he plans to build a hatching pond and ponds to keep grownup fishes and supply live fishes in the market.', 'कृष्णप्रसाद ज्ञवाली बलेटक्सारमा बसी स्वस्थकर माछाको आपूर्ति गरी आयआर्जन गर्ने उद्देश्यले फलफूल तथा माछापालनमा संलग्न हुनुहुन्छ । उहाँले उत्पादन गरेका माछाको माग बढ्दो छ । उहाँले आगामी दिनमा थप पोखरीको निर्माण गरी माछा उत्पादनलाई विस्तार गर्ने लक्ष्य लिनुभएको छ । कृषिको व्यवसायिकीकरणबाट देशको संमृद्धि हुन्छ भन्ने विश्वास उहाँमा रहेको छ । ', 'img/profile/Krishna_Prasad_Gyawali.jpg', 0, '2015-07-07 10:38:16', 1),
(24, 1, 'Khadga Bir Thapa', 'खड्गविर थापा', 'Kaligandaki Krishi Farm', 'कालीगण्डकी कृषि फार्म ', 'Aiming to promote healthy living and empower youths in his village, Mr. Khadga Bir Thapa started his organic farming business that produces fresh vegetables, fish and eggs in his village. With the demand for organic vegetables only growing in the market, he aspires to expand his business to 15 ropanis of land, produce 5000 kg of fish and increase egg production in the next three years.', 'खड्गविर थापा ठूलोलुम्पकेक गाविसमा  बसी कृषि फार्म संचालन गरी ताजा अर्गानिक तरकारी, माछा र अण्डा उत्पादनमा सक्रिय हुनुहुन्छ । उहाँले कृषिको व्यवसायिकरण गरी युवाहरुलाई स्वरोजगार बनाउनु पर्ने धारणा उहाँको रहेको छ । बढ्दो अर्गानिक तरकारीको माग पूरा गर्न आफ्नो व्यवसाय विस्तार गर्ने र माछा र अण्डाको माग पूरा गर्न फार्मको उत्पादन क्षमता बढाउने सोँच उहाँको रहेको छ ।', 'img/profile/Khadga_Bir_Thapa.jpg', 0, '2015-07-07 10:38:24', 1),
(25, 1, ' Kamal Prasad Gyawali', 'कमल प्रसाद ज्ञवाली', 'Bhandari Dada Tatha Krishi Farm', 'भण्डारीडाँडा कृषि फार्म ', 'Recognizing the market for fresh organic and non-seasonal fruits, Mr. Kamal Prasad Gyawali tapped into this high potential market and started his own business just over a year ago. Using newer technology in his animal husbandry and agriculture business, Mr. Gyawali wants to build and foster a progressive business environment and contribute in Nepal’s economic development. In the next three years, he hopes to increase his investment in machineries, labor and expanding the facilities in order to increase production and meet the growing demands of the market.\r\n', 'कमल प्रसाद ज्ञवाली बलेटक्सार गाविसमा बसी संयुक्त फार्म खोली बाख्रापालन, ताजा अर्गानिक तरकारी उत्पादनमा लाग्नु भएको छ । आधुनिक सीप र प्रविधिको प्रयोग गरी कृषि फार्म संचालन गर्ने तयारी उहाँहरुको रहेको छ । उद्यमशीलताको सकारात्मक वातावरण निर्माण गरी आर्थिक विकास गर्नु पर्ने उहाँहरुको सोँच रहेको छ । आगामी दिनमा खसीको मासुको माग र ताजा तरकारीको मागलाई पूरा गर्न  व्यवसाय विस्तार गर्ने योजना बनाउनु भएको छ । \r\n', 'img/profile/Kamal_Prasad_Gyawali.jpg', 0, '2015-07-07 11:01:58', 1),
(26, 1, 'Jhupa Bagale', 'झुपा बगाले', 'Resunga Dhaka Udhyog', 'रेसुङ्गा ढाका उद्योग', 'For Jhupa Bagale, her business that produces Dhaka products is not only a means of livelihood but also the means to empower Dalit, Janajati and women from other communities. With high demand for Dhaka products in the local community and beyond, she plans to train more women to produce Dhaka, and in the next three years, produce high quality goods by publicizing her business better, expanding physical facilities, market analysis, and using newer technologies.\r\n', 'झुपा बगाले तम्घासमा ढाका उद्योग संचालन गर्नुहुन्छ । उहाँले ढाका उद्योगमार्फत आयआर्जन र विपन्न समुदायको सशक्तिकरण गर्न सकिने विश्वास गर्नुहुन्छ । उहाँले उत्पादन गरेका ढाकाका सामग्रीहरुको माग बढ्दो छ । उहाँले आफ्नो व्यवसायलाई विस्तार गरी वेरोजगार महिलाहरुलाई रोजगार बनाउने र गुणस्तरीय ढाका उत्पादन गर्ने लक्ष्य लिनु भएको छ । उहाँको ढाका उद्योगमा थप आधुनिक प्रविधिको प्रयोग गर्ने सोँच रहेको छ ।\r\n', 'img/profile/Jhupa_Bagale.jpg', 0, '2015-07-07 11:01:17', 1),
(27, 1, 'Induwar Gyawali', 'इन्दुवर ज्ञवाली', 'Shree Thorgeli Organic Gud Udhyog', 'थोर्गेली अर्गानिक गुँड उद्योग ', 'In the scenario where market for sugarcane was lacking, Induwar Gyawali established Shree Thorgeli Organic Gud Udhyog to bridge this gap and to foster market for sugar cane based products. Her business produces fresh organic sugar cane juice which is sold both locally and nationally. In the next three years, she aims to expand her business to meet the growing demand for sugarcane by using modern equipment, increasing working capacity of the laborers and also improving the quality of her products.', 'इन्दुवर ज्ञवाली थानपति गाविसमा बसी अर्गानिक गुँड उत्पादन गर्नुहुन्छ । उहाँको गुँडको लोकप्रियता बढ्दो छ । जिल्लाभित्र मात्र होइन जिल्लाबाहिरसमेत उहाँले गुँड निर्यात गर्नुहुन्छ । गुँड उत्पादनमा नवीनता ल्याइ गुँडबाट चकलेट निर्माण गरी विदेश निर्यात गर्ने योजना उहाँको रहेको छ ।\r\n', 'img/profile/Induwar_Gyawali.jpg', 0, '2015-07-07 10:38:50', 1),
(28, 1, 'Indra Bahadur Damarpal', 'इन्द्रबहादुर डम्मरपाल', 'Sahakari Kheti (Bangur Palan)', ' बंगुरपालन ', 'Mr Indra Bahadur Damarpal uses advanced shelters to rear healthy pigs to cater to the high demand pig meat market. His business is focused towards the Dalit and Janajati community. In the next three years, he plans to expand his business to provide service in other neighboring districts as well.\r\n', 'इन्द्रबहादुर डम्मरपाल विरबास गाविसमा बसी वंगुरपालनमा सक्रिय कृषक हुनुहुन्छ । उहाँले आधुनिक खोर निर्माण गरी वंगुर पालन गरिरहनु भएको छ । उहाँले वंगुरको मासुको मागलाई पूरा गर्न यो पेशा अंगाल्नु भएको हो । उहाँले स्वस्थ वंगुरको मासु जिल्लाभित्र विक्री गरिरहनु भएको छ । आगामी दिनमा गुल्मीबाहिर समेत निर्यात गर्न सक्ने गरी व्यवसायको विस्तार गर्ने योजना उहाँको रहेको छ ।  ', 'img/profile/Indra_Bahadur_Damarpal.jpg', 0, '2015-07-07 10:39:01', 1),
(34, 1, 'Gyan Bahadur Malla', 'ज्ञानबहादुर मल्ल', ' Suntala Kheti', 'सुन्तला कृषक ', 'Recognizing that systematic orange farming has a huge potential, Mr Gyan Bahadur Malla established his orange farm not just to make a living for himself but also to attract unemployed youths and to make his village a popular tourist destination for orange farming. He plans to expand the business from 250 orange trees to 750 orange trees in just 3 years and sell not only oranges but also open an orange juice factory.\r\n', 'ज्ञानबहादुर मल्ल नयाँगाउँमा व्यवसायिक सुन्तला खेती गर्नु हुन्छ । उहाँ आफूमात्र रोजगार बन्ने नभइ अरु युवाहरुलाई समेत यस पेशामा आकर्षिक गर्ने गरी क्रियाशील हुनुहुन्छ । उहाँले सिगो गाउँँलाई नै सुन्तला बगैचा बनाइ पर्यटकीय गन्तव्य बनाउने सोच रहेको छ । आगामी दिनमा ७५० सुन्तलाको वगैचा बनाइ जुस उत्पादनमा लाग्ने योजना उहाँको रहेको छ । \r\n', 'img/profile/Gyan_Bahadur_Malla.jpg', 0, '2015-07-07 10:45:59', 1),
(35, 1, 'Gun Bahadur Thapa', 'गुनबहादुर थापा', 'Chandisthan Bakhra Farm', 'चण्डीथान बाख्रा फार्म', 'Mr. Gun Bahadur Thapa’s farm uses advanced cages and technology to meet the demand for fresh and healthy goat meat in the local market. In the next three years, he aspires to increase the capacity of his business by increasing the number of cages, using advanced equipment for castration and expanding his business to Rupandehi and Kathmandu. \r\n', 'गुनबहादुर थापा रेसुङ्गा नगरपालिका –१४ मा व्यवसायिक बाख्रा फार्म संचालन गर्नुुहुन्छ । उहाँले आधुनिक खोर निर्माण गरी बाख्रा पालन गरिरहनु भएको छ । स्वस्थ खसीको मासु आपूर्ति गरी आयआर्जन गर्ने लक्ष्य राखी स्थापना भएको हो । फार्मलाई थप विस्तार गरी रुपन्देही र काठमाडौंमा समेत खसी निर्यात गर्ने सोच उहाँको रहेको छ । बाख्रा पालनमा आधुनिक प्रविधिको प्रयोगमा उहाँको जोड रहेको छ । ', 'img/profile/Gun_Bahadur_Thapa.jpg', 0, '2015-07-07 10:45:59', 1),
(36, 1, 'Gokarna Bhujel', 'गोकर्ण भुजेल', 'Supadeurali Krishi Tatha Pashu Farm', 'सुपा देउराली कृषि तथा पशु फार्म', 'Although only a year old, Mr. Gokarna Bhujel’s business has already captured the market for fresh vegetables, pig and goat meat. New it may be, but under Mr. Bhujel’s leadership, this business holds a strong growth potential in the future. He plans to bolster his business by building his knowledge on prevention of diseases in his plants and animals, using modern equipment and proceeding in a systematic way.', 'गोकर्ण भुजेल संयुक्त रुपमा कृषि फर्म सिमीचौर गाविसमा स्थापना गरी तरकारी र मासु उत्पादनमा लाग्नु भएको छ । खसी, सुँगुर र तरकारी उत्पादन गरी बजारमा पुराउने योजना उहाँहरुको रहेको छ । आगामी दिनमा रोग, किरालाई नियन्त्रण गर्न आधुनिक प्रविधिको प्रयोग गरी व्यवसायलाई थप व्यवस्थित बनाउने सोच उहाँहरुको छ । \r\n', 'img/profile/Gokarna_Bhujel.jpg', 0, '2015-07-07 10:45:59', 1),
(37, 1, 'Ganesh Prasad Gyawali', 'गणेशप्रसाद ज्ञवाली', 'Durga Gai Bhaisi Palan Tatha Krishi Farm', ' दुर्गा गाइभैसी पालन तथा कृषि फार्म', 'Seeing a potential market for fresh organic vegetables and good quality dairy products, Mr. Ganesh Prasad Gyawali started his own organic farming business 13 years ago. With the belief that the Nepal’s economic prosperity relies on agriculture development, Mr Gyawali plans to contribute by expanding his business and quadrupling his production in the next three years.', 'गणेशप्रसाद ज्ञवाली रुरु गाविसमा बसी व्यवसायिक दूध उत्पादन र तरकारी खेती गर्ने कृषक हुनुहुन्छ । उहाँले व्यवसायिक अर्गानिक कृषि गर्न लागेको १३ वर्ष भयो । कृषिको विकासबाट नेपालको समृद्धि संभव छ भन्ने उहाँको विश्वास रहेको छ । उहाँले आफ्नो व्यवसायलाई विस्तार गरी थप व्यवस्थित गर्ने उहाँको लक्ष्य रहेको छ । ', 'img/profile/Ganesh_Prasad_Gyawali.jpg', 0, '2015-07-07 10:45:59', 1),
(38, 1, 'Durga Gyawali', 'दुर्गा ज्ञवाली ', 'Jaivik Krishi Utpadan', 'जैविक कृषि उत्पादन', 'Knowing the adverse impacts of pesticides, Ms. Gyawali started organic farming that currently serves fresh and healthy vegetables to the entire village. With an ever increasing demand for organic food, she intends to double the production by introducing technology in the upcoming days. She has been able to employee forty-two locals till date and wishes to provide opportunities for many others youths to discourage foreign employment.\r\n', 'दुर्गा ज्ञवाली थानपति गाविसमा बसी अर्गानिक तरकारी उत्पादन गर्ने कृषक हुनुहुन्छ । गुल्मीको थानपतिमा उहाँले अर्गानिक तरकारी उत्पादन गरिरहनु भएको छ । उहाँले उत्पादन गरेको अर्गानिक तरकारीको माग बढदो छ । उहाँले नयाँ प्रविधिको प्रयोग गरी बढी भन्दा बढी अर्गानिक तरकारी उत्पादन गर्ने सोँच राख्नु भएको छ । उहाँले व्यवसायिक तरकारी खेतीबाट युवाहरुको विदेश पलायन रोकी रोजगारी सिर्जना गर्नुपर्छ भन्ने धारणा रहेको छ । \r\n', 'img/profile/Durga_Gyawali.jpg', 0, '2015-07-07 10:58:22', 1),
(39, 1, 'Dipika Thapa', 'दिपिका थापा', 'Shrijansheel Paral Chappal', ' सिर्जनशील पराल चप्पल उद्योग ', 'Ms. Thapa started producing handmade hay sandals with an objective of capitalizing the skill set she possess. With the demand for her sandals increasing, she hopes to employ at least two more people in the upcoming year and increasing her production. She prides being an entrepreneur and mobilizing the otherwise wasted raw materials.\r\n', 'दिपिका थापा, गुल्मी जिल्लाको रिडीमा बसेर परालको चप्पल उत्पादन गर्ने युवा व्यवसायी हुन । उनको चप्पलको माग दिनप्रति दिन बढ्दो छ । उहाँले आफ्नो व्यवसायलाई विस्तार गरी थप जनशक्तिलाई रोजगार बनाउने लक्ष्य लिनु भएको छ । उहाँ खेर गइरहेको कच्चा पदार्थबाट पराल चप्पल उत्पादन गरेकोमा गौरव गर्नुहुन्छ । \r\n', 'img/profile/Dipika_Thapa.jpg', 0, '2015-07-07 10:58:22', 1);
INSERT INTO `candidate` (`id`, `poll_id`, `name`, `name_np`, `organization`, `organization_np`, `detail`, `detail_np`, `photo`, `votes`, `timestamp`, `active`) VALUES
(40, 1, 'Chuman Bahadur Gharti Magar', 'चुमानबहादुर घर्ती मगर ', 'Malarani Mauri Palan Kendra', 'मालारानी मौरी पालन केन्द्र ', 'With most of the villagers engaged in farming and animal husbandry, Mr. Magar wanted to start something unconventional; hence he started beekeeping business. Today, he is renowned in his village for pure natural honey and wax produced in his farm. He has, so far, trained seventeen other youths interested in the sector. In future days, he aspires to expand his venture into a factory and export the products in international  market.\r\n', 'चुमानबहादुर घर्ती मगर वामी गाविसको मालारानीमा बसी मौरीपालन गर्ने उद्यमी हुनुहुन्छ । उहाँले वामीको मालारानीमा माहुरीपालन गरी शुद्ध प्राकृतिक मह उत्पादन गर्नुहुन्छ । उहाँले माहुरी पालनलाई थप विस्तार गर्ने योजना बनाउनु भएको छ । उत्पादित महलाई विकसित देशमा निर्यात गर्ने सोँच उहाँले लिनु भएको छ । \r\n', 'img/profile/Chuman_Bahadur_Gharti_Magar.jpg', 0, '2015-07-07 10:58:22', 1),
(41, 1, 'Chabilal Aryal', 'छविलाल अर्याल कृषि,', ' Krishi Mauri Tatha Bakhra Palan Samuha', 'माहुरी तथा बाख्रा पालन समूह', 'Producing a range of products from vegetables, honey to goat meat, Mr Chabilal’s business is truly distinctive. Plus, the business’ focus on helping the society’s impoverished community, makes it more special. In the next three years, he envisions strengthening his business by raising the number of hives from 10 to 100, increasing the number of goats and expanding in a systematic way.', 'छविलाल अर्यालले हर्दिनेटा गाविसमा बसी सामूहिक रुपमा तरकारी, माहुरी पालन तथा बाख्रापालन गरिरहनु भएको छ । उहाँले सामूहिक आर्थिक उपार्जनमार्फत समुदायको सशक्तिकरण गर्न सकिने मान्यता राख्नु हुन्छ । आगामी दिनमा व्यवस्थित तवरले बाख्रापालन, तरकारी र मौरीपालनको विस्तार गरी उद्यमशीलताको विकास गर्ने लक्ष्य उहाँले लिनु भएको छ । सामूहिक आर्थिक विकासले नै रोजगारीको सिर्जना गर्ने सोँच उहाँको रहेको छ । \r\n', 'img/profile/Chabilal_Aryal.jpg', 0, '2015-07-07 10:58:22', 1),
(42, 1, 'Bir Bahadur Karki', 'विरवहादुर कार्की', 'Resunga Madane Jadibuti tatha krishi utpadan', 'रेसुङ्गा मदाने जडिवुटी तथा कृषि उत्पादन ', 'Mr. Bir Bahadur Karki and his venture are both exceptional. While his business produces medicinal herbs, fruit sapling, biodiesel, and distilled scent, Mr. Karki makes the young people in his district self-reliant by providing employment opportunities. Not just the young people, he wants to make the village self-reliant by increasing the production of medicinal herbs and exporting outside his village. In the next three years, he plans to double his investment to build a modern nursery, increase human resources and strengthen his business with a focus on marketing.\r\n', 'छविलाल अर्यालले हर्दिनेटा गाविसमा बसी सामूहिक रुपमा तरकारी, माहुरी पालन तथा बाख्रापालन गरिरहनु भएको छ । उहाँले सामूहिक आर्थिक उपार्जनमार्फत समुदायको सशक्तिकरण गर्न सकिने मान्यता राख्नु हुन्छ । आगामी दिनमा व्यवस्थित तवरले बाख्रापालन, तरकारी र मौरीपालनको विस्तार गरी उद्यमशीलताको विकास गर्ने लक्ष्य उहाँले लिनु भएको छ । सामूहिक आर्थिक विकासले नै रोजगारीको सिर्जना गर्ने सोँच उहाँको रहेको छ । ', 'img/profile/Bir_Bahadur_Karki.jpg', 0, '2015-07-07 10:58:22', 1),
(43, 1, 'Bir Bahadur Bishwakarma', 'विरबहादुर विश्वकर्मा ', 'Sainik Grill Tatha Krishi Aujar', 'सैनिक ग्रिल तथा कृषि औजार', 'Mr. Bishwakarma started his venture as a blacksmith to produce necessary farming tools with a vision to contribute to the agro environment in his village. He started off by creating agricultural tools as per the demand of the local farmers and now has expanded into manufacturing other iron objects like grill, chain gate,and railing among other things. In the coming years, he plans to invest in machineries to increase the quality of his production.', 'विरबहादुर विश्वकर्मा अमरअर्वाथोक गाविसमा  बसी कृषि औजार उत्पादन गर्ने उद्योगी हुनुहुन्छ । उहाँले कृषि औजारका अतिरिक्त खुकुरी, ग्रिल, चेनगेट, रेलिङ्ग उत्पादन गर्नुहुन्छ । उहाँले यस व्यवसायलाई थप व्यवस्थित बनाउन आधुनिक मेशीन जडान गर्नु भएको छ । साथै आफ्नो व्यवसायमा थप मेशीन थप गर्ने उहाँको योजना छ । परम्परागत पेशालाई आधुनिकीकरण गरी समयानुकूलको व्यवसाय विकासमा उहाँ क्रियाशील हुनुहुन्छ  । \r\n', 'img/profile/Bir_Bahadur_Bishwakarma.jpg', 0, '2015-07-07 10:58:22', 1),
(44, 1, 'Bin Bahadur Jogi Kunwar', ' विनबहादुर जोगी कुँवर', 'Binod Krishi Farm', 'विनोद कृषि फार्म ', 'In order to meet the demand for fresh vegetables and make his village self reliant, Mr. Bin Bahadur Kunwar started his farming business seventeen years ago. He uses compost manure and organic pesticides to produce healthy and organic seasonal vegetables. In the next three years, he plans to lease an additional 5 ropanis of land to farm year-long in the total of 13 ropanis of land producing both seasonal and non-seasonal vegetables.\r\n', 'विनबहादुर जोगी कुँवर, रेसुङ्गा नगरपालिका –११ मा बसी ताजा तरकारी उत्पादन गर्नुहुन्छ । उहाँले १७ वर्षदेखि यो व्यवसाय गरिरहनु भएको छ । उहाँले आफै कम्पोष्ट मल उत्पादन गरी स्वस्थवद्र्धक अर्गानिक तरकारी उत्पादन र विक्री गर्नुहुन्छ । उहाँले हाल १३ रोपनी जग्गामा मौसमी र वेमौसमी तरकारी उत्पादन गर्नुहुन्छ । उहाँले आगामी दिनमा व्यवसाय विस्तार गर्ने योजना बनाउनु भएको छ । ', 'img/profile/Bin_Bahadur_Jogi_Kunwar.jpg', 0, '2015-07-07 10:58:22', 1),
(45, 1, 'Bikash Pant', 'विकास पन्त', 'Bikash Nursery', 'विकास नर्सरी', 'An avid nature lover, Mr Bikash Pant established his nursery to earn a living by selling seasonal and non seasonal vegetable plants as well as promoting environmental conservation. In the next three years he plans to expand his business by building proper infrastructures like tunnel for irrigation, additional screen house and greenhouse to grow more plants, and investing in rainwater harvesting.\r\n', 'विकास पन्त हर्दिनेटा गाविसमा बसी नर्सरी संचालन गर्नुहुन्छ । उहाँले आफ्नो नर्सरी मौसमी तथा वेमौसमी तरकारी तथा विरुवा उत्पादन गरी विक्री गर्नुहुन्छ । उहाँको अर्गानिक तथा वातावरणमैत्री कृषि उत्पादनमा जोड रहेको छ । पन्तले जैविक विविधताका पारखी आफ्नो नर्सरीमा धेरै प्रकारका विरुवा उत्पादन गर्नु भएको छ । उहाँले प्लाष्टिक टनेल, ग्रिनहाउस, आकाशे पानी संकलन र सिचाइ गर्नु भएको छ । ', 'img/profile/Bikash_Pant.jpg', 0, '2015-07-07 10:58:22', 1),
(46, 1, 'Bal Krishna Bhandari', 'बालकृष्ण भण्डारी', 'New Resunga Dugdha Dairy Udhyog', 'न्यू रेसुङ्गा दूध डेरी उद्योग ', 'With the aim to systematize market mechanism and produce quality dairy products, Mr. Bhandari started his dairy firm six years ago. He bridges the gap between the local farmers and the market by collecting milk produced in his village, a portion of which he uses to manufacture various dairy products, and distributes the remainder in the market. In the next three years, he plans to expand his market and sell his products even outside the district.\r\n', 'बालकृष्ण भण्डारी तम्घासमा बसेर ६ वर्षदेखि  दुध डेरी उद्योग संचालन गर्नु भएको छ । उहाँले उत्पादन र बजारबीचको सम्बन्धलाई व्यवस्थित बनाइ गुणस्तरीय दूधजन्य परिकार उपलब्ध गराउने उहाँको लक्ष्य रहेको छ । उहाँले गाउँमा रहेको दूध संकलन गरेर दूध र दूधका परिकारहरु तम्घास साथै जिल्ला बाहिर पठाउने योजना रहेको छ ।\r\n', 'img/profile/Bal_Krishna_Bhandari.jpg', 0, '2015-07-07 10:58:22', 1),
(47, 1, 'Arjun Kanauje', 'अर्जुन कनौजे', ' Arjun Taja Tarkari Tatha Dudh Utpadan', 'अर्जुन ताजा तरकारी तथा दूध उत्पादन ', 'With almost a decade long experience in commercialized farming, Mr. Kanauje operates a farm which today is considered a model farm in Gulmi district. In addition to producing fresh vegetables and dairy products, his enterprise has been training people who are keen to start their career in this field. He firmly believes that problems of unemployment and immigration can be solved by mobilizing the locally available resources and skills.', 'अर्जुन कनौजे अश्लेवा गाविस निबासी अनुभवी व्यवसायिक युवा कृषक हुनुहुन्छ । उहाँले व्यवसायिक रुपमा ताजा तरकारी र दूध उत्पादनको कार्य गर्नु भएको छ । उहाँले नमुना कृषि फर्म संचालन गर्नु भएको छ । स्थानीय साधन र स्रोतमा आधारित व्यवसायिक कृषिबाट नै रोजगारीको सिर्जना सकिने विश्वास उहाँको रहेको छ ।  \r\n', 'img/profile/Arjun_Kanauje.jpg', 0, '2015-07-07 10:58:22', 1),
(48, 1, 'Ajay Kapur Shrestha', 'अजय कपुर श्रेष्ठ', 'Shree Kumaltari Krishi Tatha Bakhra Palan Farm', ' श्री  कुमालटारी कृषि तथा बाख्रा पालन फार्म ', 'Mr. Ajay Kapur Shrestha’s desire to be financially independent led him to open a farm that produces and supplies fresh goat meat in his village. Knowing the importance of knowledge, he plans to participate in programs to build his skills and learn about strengthening his business. In the future, he plans to modernize his business by making a dipping tank, opening modern cold store, building bigger and advanced cages to scale up both production and profit.\r\n', 'अजय कपुर श्रेष्ठले धुर्कोट रजस्थलमा बसी आर्थिक रुपमा आत्म निर्भर बन्न आफ्नै गाउँमा बाख्रा फार्म संचालन गर्नु भएको छ । उहाँले उच्च स्तरीय व्यवसायिक ज्ञान र सीप हासिल गरी आधुनिक र व्यवसायिक बाख्रा पालन गर्ने सोँच लिनु भएको छ । भविष्यमा व्यवसायलाई थप सशक्त पार्दै डिपिङ्ग टेङ्क, चिस्यान केन्द्र बनाउने लक्ष्य उहाँको रहेको छ । व्यवसाय विस्तार गरी उत्पादन र रोजगारी वृद्धि गर्ने उद्देश्य लिइ व्यवसायिक बाख्रा पालनमा क्रियाशील हुनुहुन्छ । ', 'img/profile/Ajay_Kapur_Shrestha.jpg', 0, '2015-07-07 10:59:59', 1);

-- --------------------------------------------------------

--
-- Table structure for table `vote`
--

CREATE TABLE IF NOT EXISTS `vote` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `candidate_id` int(3) NOT NULL,
  `fbuserid` bigint(25) NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=9 ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
